// Mocks generated by Mockito 5.4.2 from annotations
// in movie_db_app/test/unit_testing/bloc/movie_bloc_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_db_app/src/core/util/states.dart' as _i4;
import 'package:movie_db_app/src/data/datasource/remote/movie_list_api_service.dart'
    as _i3;
import 'package:movie_db_app/src/data/repository/movie_repository_class.dart'
    as _i2;
import 'package:movie_db_app/src/domain/usecase/implementation/movies_usecase_impl.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieListApiService_1 extends _i1.SmartFake
    implements _i3.MovieListApiService {
  _FakeMovieListApiService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_2<T> extends _i1.SmartFake implements _i4.DataState<T> {
  _FakeDataState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesUseCase extends _i1.Mock implements _i5.MoviesUseCase {
  MockMoviesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieRepository);

  @override
  set repository(_i2.MovieRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.MovieListApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeMovieListApiService_1(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i3.MovieListApiService);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: '',
      ) as String);

  @override
  _i6.Future<_i4.DataState<dynamic>> call() => (super.noSuchMethod(
        Invocation.method(
          #repositoryCall,
          [],
        ),
        returnValue:
            _i6.Future<_i4.DataState<dynamic>>.value(_FakeDataState_2<dynamic>(
          this,
          Invocation.method(
            #repositoryCall,
            [],
          ),
        )),
      ) as _i6.Future<_i4.DataState<dynamic>>);
}
