// Mocks generated by Mockito 5.4.2 from annotations
// in movie_db_app/test/unit_testing/bloc/movie_bloc_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_db_app/src/core/util/categories.dart' as _i7;
import 'package:movie_db_app/src/core/util/states.dart' as _i4;
import 'package:movie_db_app/src/data/repository/movie_repository_from_apiservice.dart'
    as _i2;
import 'package:movie_db_app/src/data/repository/movie_repository_from_database.dart'
    as _i3;
import 'package:movie_db_app/src/domain/usecase/implementation/movies_usecase_impl.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepoFromApiService_0 extends _i1.SmartFake
    implements _i2.MovieRepoFromApiService {
  _FakeMovieRepoFromApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieRepoFromDB_1 extends _i1.SmartFake
    implements _i3.MovieRepoFromDB {
  _FakeMovieRepoFromDB_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_2<T> extends _i1.SmartFake implements _i4.DataState<T> {
  _FakeDataState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesUseCase extends _i1.Mock implements _i5.MoviesUseCase {
  MockMoviesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepoFromApiService get repoFromApiService => (super.noSuchMethod(
        Invocation.getter(#repoFromApiService),
        returnValue: _FakeMovieRepoFromApiService_0(
          this,
          Invocation.getter(#repoFromApiService),
        ),
      ) as _i2.MovieRepoFromApiService);

  @override
  set repoFromApiService(_i2.MovieRepoFromApiService? _repoFromApiService) =>
      super.noSuchMethod(
        Invocation.setter(
          #repoFromApiService,
          _repoFromApiService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.MovieRepoFromDB get repoFromDB => (super.noSuchMethod(
        Invocation.getter(#repoFromDB),
        returnValue: _FakeMovieRepoFromDB_1(
          this,
          Invocation.getter(#repoFromDB),
        ),
      ) as _i3.MovieRepoFromDB);

  @override
  _i6.Future<_i4.DataState<dynamic>> call([_i7.CategoryEnum? categoryCall]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryCall],
        ),
        returnValue:
            _i6.Future<_i4.DataState<dynamic>>.value(_FakeDataState_2<dynamic>(
          this,
          Invocation.method(
            #call,
            [categoryCall],
          ),
        )),
      ) as _i6.Future<_i4.DataState<dynamic>>);
}
